"""Colour engine — the Quarto half.

A near-verbatim port of the blog's `hooks/palette.py`. It is the reason this
experiment exists: the MkDocs build generates its stylesheets and its mermaid
`classDef` blocks from `palette.yml` at build time, and the question was whether
that survives a move to Quarto. It does, as a pre-render script, with the colour
logic in `fallcolor.Palette` untouched.

Generates, every render:

  * `_palette-light.scss`, `_palette-dark.scss` — Bootstrap defaults plus the
    --fall-* / --ink-* tokens, and the handful of --md-* names the ported posts
    still reference from their raw HTML
  * a `classDef` block in every flowchart that asks for one

`p.check()` runs first, so an illegible palette fails the render rather than the
reader — same contract as the MkDocs hook.
"""

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import curriculum  # noqa: E402
from fallcolor import Palette, PaletteError  # noqa: E402

# Only flowcharts take classDef. A sequenceDiagram would throw a parse error,
# and one parse error blanks every diagram on the page.
_FENCE = re.compile(
    r"^(?P<indent>[ \t]*)```+[ \t]*\{?mermaid\}?[ \t]*$(?P<body>.*?)^(?P=indent)```+[ \t]*$",
    re.M | re.S,
)
_FLOWCHART = re.compile(r"^\s*(graph|flowchart)\b", re.M)
_USED = re.compile(r":::(\w[\w-]*)|^\s*class\s+[\w,\s-]+?\s+(\w[\w-]*)\s*$", re.M)
_FM = re.compile(r"\A---\n(.*?)\n---\n", re.S)


def scss(pal: Palette, scheme: str) -> str:
    """One generated stylesheet: Bootstrap defaults, then the tokens."""
    r = lambda name: pal.role(name, scheme).hex  # noqa: E731
    ground, tint = r("ground"), r("ground-tint")
    text = pal.grounds["slate"] if scheme == "light" else pal.grounds["paper"]

    defaults = [
        f"$primary: {r('primary')};",
        f"$link-color: {r('link')};",
        f"$body-bg: {ground};",
        f"$body-color: {text};",
        f"$code-bg: {tint};",
        "$font-size-root: 17px;",
        '$font-family-sans-serif: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;',
    ]

    tokens = [f"  --fall-{s.name}: {s.hex};" for s in pal]
    tokens += [
        f"  --ink-{name}: {pal.as_ink(name, scheme).hex};" for name in pal.hues
    ]
    # The ported posts carry raw HTML written against Material's variable names.
    # Defining them here is cheaper than rewriting a thousand lines of markup.
    #
    # --md-code-bg-color is deliberately the dark ground in BOTH schemes. Those
    # widgets hardcode `color: #f8fafc` and only ever had contrast because
    # Material's dark mode happened to make this token dark; on paper they are
    # near-invisible, which is a live bug on the MkDocs site's light mode too.
    # Pinning it dark is what the markup always meant.
    tokens += [
        f"  --md-code-bg-color: {pal.grounds['slate']};",
        f"  --md-typeset-table-color: {pal.role('ink-strong', scheme).hex};",
        f"  --md-accent-fg-color: {r('accent')};",
    ]

    return (
        f"/* Generated by tools/prerender.py from palette.yml — do not edit. */\n"
        f"/*-- scss:defaults --*/\n" + "\n".join(defaults) + "\n\n"
        f"/*-- scss:rules --*/\n:root {{\n" + "\n".join(tokens) + "\n}\n"
    )


def inject(markdown: str, pal: Palette, set_name: str) -> tuple[str, int]:
    """Append the classDefs a diagram actually references. Idempotent: a block
    that already defines its own is left alone, so re-rendering is a no-op."""
    defs = pal.classdefs(set_name)
    known = {d.split()[1] for d in defs}
    count = 0

    def repl(m: re.Match) -> str:
        nonlocal count
        body = m.group("body")
        if not _FLOWCHART.search(body) or "classDef" in body:
            return m.group(0)
        wanted = {g for pair in _USED.findall(body) for g in pair if g} & known
        if not wanted:
            return m.group(0)
        count += 1
        needed = "\n".join(d for d in defs if d.split()[1] in wanted)
        return f"{m.group('indent')}```{{mermaid}}{body.rstrip()}\n{needed}\n{m.group('indent')}```"

    return _FENCE.sub(repl, markdown), count


def palette_of(text: str) -> str:
    """The `palette:` key in a post's frontmatter, or the default set."""
    m = _FM.match(text)
    if m:
        for line in m.group(1).splitlines():
            if line.startswith("palette:"):
                return line.split(":", 1)[1].strip() or "default"
    return "default"


def main() -> int:
    try:
        pal = Palette.load(os.path.join(HERE, "palette.yml"))
        pal.check()
    except PaletteError as exc:
        print(f"palette: {exc}", file=sys.stderr)
        return 1

    for scheme in ("light", "dark"):
        path = os.path.join(ROOT, f"_palette-{scheme}.scss")
        with open(path, "w") as fh:
            fh.write(scss(pal, scheme))
        print(f"palette: wrote {os.path.basename(path)}")

    total = 0
    for dirpath, _, names in os.walk(os.path.join(ROOT, "blogs")):
        for name in names:
            if not name.endswith(".qmd"):
                continue
            path = os.path.join(dirpath, name)
            with open(path) as fh:
                before = fh.read()
            after, n = inject(before, pal, palette_of(before))
            if n:
                with open(path, "w") as fh:
                    fh.write(after)
                total += n
    print(f"palette: injected classDefs into {total} flowchart(s)")

    # The curriculum half: _sidebar.yml, the syllabus pages, and the per-page
    # furniture. Non-zero here fails the render, which is the point.
    return curriculum.run()


if __name__ == "__main__":
    raise SystemExit(main())
